---
- name: MacOS install
  hosts: localhost
  connection: local

  tasks:
    - name: Link to Brewfile
      ansible.builtin.file:
        src: ~/.dotfiles/Brewfile
        dest: ~/Brewfile
        state: link

    - name: Link to .zshrc
      ansible.builtin.file:
        src: ~/.dotfiles/.zshrc
        dest: ~/.zshrc
        state: link

    - name: Link to .vim
      ansible.builtin.file:
        src: ~/.dotfiles/.vim
        dest: ~/.vim
        state: link

    - name: Link to .vimrc
      ansible.builtin.file:
        src: ~/.dotfiles/.vimrc
        dest: ~/.vimrc
        state: link

    - name: Link to .config
      ansible.builtin.file:
        src: ~/.dotfiles/.config
        dest: ~/.config
        state: link

    - name: Install oh-my-zsh
      ansible.builtin.command:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: ~/.dotfiles/.oh-my-zsh
      notify:
        - Move oh-my-zsh
        - Link to .oh-my-zsh

    - name: Link to .oh-my-zsh
      ansible.builtin.file:
        src: ~/.dotfiles/.oh-my-zsh
        dest: ~/.oh-my-zsh
        state: link

    # - name: Brew bundle
    #   ansible.builtin.command:
    #     cmd: brew bundle
    #     chdir: ~

  handlers:
    - name: Move oh-my-zsh
      ansible.builtin.command:
        cmd: mv ~/.oh-my-zsh ~/.dotfiles/

    - name: Link to .oh-my-zsh
      ansible.builtin.file:
        src: ~/.dotfiles/.oh-my-zsh
        dest: ~/.oh-my-zsh
        state: link
