---
- name: MacOS install
  hosts: localhost
  connection: local

  tasks:
    - name: Link to Brewfile
      ansible.builtin.file:
        src: ~/Brewfile
        dest: ~/.dotfiles/Brewfile
        state: link

    - name: Link to .zshrc
      ansible.builtin.file:
        src: ~/.zshrc
        dest: ~/.dotfiles/.zshrc
        state: link

    - name: Link to .vim
      ansible.builtin.file:
        src: ~/.vim
        dest: ~/.dotfiles/.vim
        state: link

    - name: Link to .vimrc
      ansible.builtin.file:
        src: ~/.vimrc
        dest: ~/.dotfiles/.vimrc
        state: link

    - name: Link to .config
      ansible.builtin.file:
        src: ~/.config
        dest: ~/.dotfiles/.config
        state: link

    - name: Link to .oh-my-zsh
      ansible.builtin.file:
        src: ~/.oh-my-zsh
        dest: ~/.dotfiles/.oh-my-zsh
        state: link

    # - name: Brew bundle
    #   ansible.builtin.command:
    #     cmd: brew bundle
    #     chdir: ~
